[tool:pytest]
DJANGO_SETTINGS_MODULE = ai_service.settings
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --tb=short --strict-markers --reuse-db
testpaths = tests
markers =
    unit: unit tests
    integration: integration tests