name: AI Service CI

on:
  push:
    paths:
      - 'ai_service/**'
    branches: [main]
  pull_request:
    paths:
      - 'ai_service/**'
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: 🔧 Install system dependencies (portaudio for PyAudio)
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev

      - name: 📦 Install dependencies
        working-directory: ai_service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🧪 Run tests with Pytest
        working-directory: ai_service
        run: |
          if [ -d tests ]; then
            pytest tests --maxfail=5 --disable-warnings -v
          else
            echo "No tests directory found. Running standalone test scripts..."
            python test_runner.py || true
            python test_progressive_system.py || true
            python test_agent_connectivity.py || true
          fi
