name: HelplineV1 CI
permissions:
  contents: read

on:
  push:
    paths:
      - 'helplinev1/**'
    branches: [main]
  pull_request:
    paths:
      - 'helplinev1/**'
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build PHP image
        run: |
          docker build -t helpline-php helplinev1/docker/php

      - name: Build NGINX image
        run: |
          docker build -t helpline-nginx helplinev1/docker/nginx

      - name: Run Docker Compose
        working-directory: helplinev1
        run: |
          docker compose up -d

      - name: Wait for app to be ready
        run: sleep 20  # Allow containers to settle

      - name: Check web endpoint
        run: |
          curl -I http://localhost || echo "Web check failed"
