name: HelplineV1 CI

permissions:
  contents: read

on:
  push:
    paths:
      - 'helplinev1/**'
    branches: [main]
  pull_request:
    paths:
      - 'helplinev1/**'
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: helpline
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build PHP image
        run: |
          docker build -t helpline-php helplinev1/docker/php

      - name: Build NGINX image
        run: |
          docker build -t helpline-nginx helplinev1/docker/nginx

      - name: Run Docker Compose
        working-directory: helplinev1
        run: |
          docker-compose up -d

      - name: Wait for services to be ready
        run: sleep 20

      - name: Check Web Endpoint
        run: |
          curl -I http://localhost || echo "Web check failed"

      - name: Tear down Docker Compose
        if: always()
        working-directory: helplinev1
        run: |
          docker-compose down
